AGID-475 Allineare lo stile dei commenti a quanto presente nel mockup (hqCfvHZy) - Aggiugne stile e html per adattare a mockup.
italia/docs-italia-theme pull request #137
Opened 2018-10-11 08:59 UTC by ninomarrazzo

2018-10-11 10:12 UTC, pdavide requested changes
<img width="676" alt="schermata 2018-10-11 alle 11 49 34" src="https://user-images.githubusercontent.com/9119858/46797151-aa1d7300-cd4e-11e8-8982-de53ad0c6ab0.png">

- Manca il segno +/- per espandere/collassare i commenti
- Manca la freccia per espandere/collassare i singoli commenti
- Il testo dovrebbe essere sans-serif

2018-10-11 10:44 UTC, pdavide requested changes
<img width="642" alt="schermata 2018-10-11 alle 12 20 25" src="https://user-images.githubusercontent.com/9119858/46797723-3aa88300-cd50-11e8-8ccf-46bc03edce07.png">

- Il testo interno alla textarea non dovrebbe essere bold.

<img width="773" alt="schermata 2018-10-11 alle 12 34 05" src="https://user-images.githubusercontent.com/9119858/46798349-fd44f500-cd51-11e8-8192-5e7290bde586.png">

- La textarea dovrebbe avere una `min-height: 5em;`
- I bottone per inviare il commento dovrebbe avere lo [stile "primary" di bootstrap italia](https://italia.github.io/bootstrap-italia/docs/componenti/bottoni/#small).
- Il bottone "annulla" può essere eliminato
- Il testo di aiuto per la sintassi markdown dovrebbe essere contenuto in un [popover che si apre verso il basso](https://italia.github.io/bootstrap-italia/docs/componenti/popover/#le-quattro-direzioni) cliccando su un bottone "suggerimenti".
- Il bottone "suggerimenti" dovrebbe avere lo [stile "secondary outline" di bootstrap italia](https://italia.github.io/bootstrap-italia/docs/componenti/bottoni/).
- Il testo placeholder dentro la textarea dovrebbe essere: "Scrivi qui un commento. Per formattare il testo puoi usare Markdown, clicca sul bottone "suggerimenti" per vedere degli esempi."
- Il testo "Caratteri richiesti: -20" dovrebbe avere una `font-size: 0.8em` ed essere visualizzato sulla stessa riga dei bottoni allineato a destra. Il testo dovrebbe essere "Scrivi almeno altri <num> caratteri" e poi non dovrebbe essere visibile superata la soglia richiesta.
- Al click sul bottone invia, il testo non dovrebbe essere coperto e non si dovrebbe visualizzare "Invio del commento", invece il bottone e la textarea dovrebbero passare in modalità "disabled" e dovrebbe apparire uno spin loader a destra del bottone "suggerimenti" (va bene lo stesso usato per il popup).

2018-10-11 10:56 UTC, pdavide approved these changes

2018-10-11 11:00 UTC, pdavide requested changes
<img width="761" alt="schermata 2018-10-11 alle 12 50 30" src="https://user-images.githubusercontent.com/9119858/46799434-0daa9f00-cd55-11e8-8498-3113cd67434a.png">

Il testo "Contenuto sembra poco chiaro, è una frase completa?" non dovrebbe apparire più di una volta in caso di più invii e dovrebbe essere: "Il tuo commento non sembra abbastanza comprensibile. Prova con qualcosa di semplice e lineare."

2018-10-16 07:42 UTC, ninomarrazzo reviewed
Ho apportato la modifica anche alle icone. Ora sono correttamente visualizzate. Verifico la questione della frase di errore "contenuto poco chiaro" e rieffettuo push.

2018-10-16 07:48 UTC, ninomarrazzo reviewed
Fixato anche il problema della frase di errore che si ripeteva ad ogni submit. Implemento il resto delle richieste.

2018-10-16 16:37 UTC, ninomarrazzo commented
@pdavide Ho ultimato tutte le modifiche richieste. Il codice di questa PR dovrà essere ritoccato a seguito del merge di https://github.com/italia/docs-italia-theme/pull/140.

2018-10-17 10:44 UTC, pdavide requested changes
Ti segnalo qualche ulteriore piccola rifinitura (per lo più dovute a mie imprecisioni):
- il testo dei commenti visualizzati, della data e del nome dell'organizzazione dovrebbero essere sans-serif
- Il bottone "invia" dovrebbe essere a sx e "suggerimenti" a dx
- La textarea dovrebbe avere la class `p-2` al posto di `pl-3` e `pr-3`
- Lo spin loader non dovrebbe essere interno al bottone "invia" ma esterno a destra del bottone "suggerimenti"

2018-10-18 13:08 UTC, ninomarrazzo reviewed
Dovremmo esserci!

2018-10-18 13:24 UTC, pdavide requested changes

2018-10-25 09:56 UTC, ninomarrazzo reviewed
Ho apportato le modifiche richieste.

2018-10-25 19:39 UTC, pdavide approved these changes

2018-10-26 07:34 UTC, merged