AGID-520 Verificare il funzionamento dell'integrazione con il forum anche su dispositivi mobile. (rYD7Wqsr)
italia/docs-italia-theme pull request #143
Opened 2018-10-16 10:18 UTC by ninomarrazzo

Aggiunge comportamento alternativo quando su dispositivi mobili (evita apertura popup).

2018-10-16 16:30 UTC, pdavide commented
Sembra che ci sia un conflitto perché in bc8db79bfda2f6b8fc5f53f65e3f02177e9ad332 avevi già aggiunto delle istruzioni per la rilevazione dei dispositivi mobili.

2018-10-16 16:31 UTC, pdavide requested changes
Sembra che ci sia un conflitto perché in bc8db79 avevi già aggiunto delle istruzioni per la rilevazione dei dispositivi mobili.

2018-10-18 13:13 UTC, ninomarrazzo reviewed
Anche con questa ci siamo.

2018-10-18 13:25 UTC, pdavide approved these changes

2018-10-18 13:26 UTC, merged