cambiati gli assets di base del tema, agiunta nuova struttra sass e j…
italia/docs-italia-theme pull request #64
Opened 2018-05-10 13:03 UTC by anavarro-wellnet

Cambiati gli assets di base del tema.
Aggiunta nuova struttra sass.
Aggiunto  js custom ( custom.js) con gestione keywords, navigazazione dei tioli, custom markdown.

2018-05-10 17:22 UTC, pdavide requested changes
Alcuni commenti sono solo per lasciare un appunto. Possiamo usarli per confrontarci su come procedere al meglio.
@anavarro-wellnet lascio decidere a te cosa modificare in questa PR e cosa rinviare a dopo per cercare di andare spediti, ma senza lasciare indietro troppe cose da rivedere.
@francescozaia anche una tua veloce review, nell'ottica di un'armonizzazione con bootstrap italia, di cui questo tema è uno dei primi esempi di utilizzo, mi farebbe piacere.

2018-05-15 09:40 UTC, francescozaia approved these changes
Non entro nel vostro processo di lavoro per cui approvo pur lasciando qualche commento di carattere generale.

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/layouts/footer.html
> +        <!-- <div class="">
Info di servizio: penso tu possa usare anche `{% comment %}...{% endcomment %}` così il codice non compare nell'HTML generato.

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/layouts/footer.html
> +            <div class="">
Questo si può rimuovere (se serve lo spazio attualmente occupato da `<p></p>` si può usare un `padding` al contenitore).

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/layouts/header.html
> +      <div class="doc-Italia__header-col doc-Italia__header-col--info p-2">
Sì, eviterei maiuscole e userei, nel caso decidiate di continuare ad usarlo, `docs-Italia`.

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/layouts/header.html
> +            /* Hides RTD injected html to display versions */
Nota generale: occhio a quello che inietta RTD automaticamente (almeno finché continueremo ad usare RTD).
Quando avremo DocsItalia pronto, a backend possiamo personalizzare ciò che viene iniettato.

Parliamone quando inizieremo a pubblicare su documentazioni "vere".

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/static/css/badge_only.css
> +Error: File to import not found or unreadable: theme_variables.
Questo file non mi sembra stia benissimo 😄

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/static/js/theme.js
> +ThemeToolTip.init();
Siete sicuri di non riuscire a stilare [Tooltips](https://italia.github.io/bootstrap-italia/docs/componenti/tooltip/) o [Popovers](https://italia.github.io/bootstrap-italia/docs/componenti/popover/) già presenti su Bootstrap Italia?

2018-05-15 09:40 UTC, francescozaia commented on docs-italia-theme/static/js/theme.js
> +},{}]},{},["docs-italia-theme"]);
Questo file è già molto grande, rischia di diventare di difficile manutenzione. Suggerirei di mettere in piedi almeno una semplice concatenazione su `grunt` (se non ovviamente un `module bundler`, anche se non è indispensabile su questo progetto), per avere "moduli" separati.

2018-05-15 14:46 UTC, pdavide approved these changes

2018-05-15 14:46 UTC, merged