Bootstrap italia wellnet
italia/docs-italia-theme pull request #89
Opened 2018-06-06 13:42 UTC by lmorelli986

modificato stile dell'header in vista desktop

2018-06-06 17:12 UTC, pdavide requested changes
- L'header non è visualizzato correttamente su mobile, dovrebbe essere come nel mockup.
- Il footer non è visualizzato correttamente su mobile (sistemare spaziatura tra gli elementi).

2018-06-07 10:32 UTC, pdavide commented on docs_italia_theme/layouts/footer.html
> -              {% set link_name = link.title %}
Si possiamo assumerlo, perché si tratta di elementi del tema che non possono essere modificati da chi userà il tema per i propri documenti.

2018-06-08 07:01 UTC, lmorelli986 commented on docs_italia_theme/layouts/footer.html
> -              {% set link_name = link.title %}
Ok perfetto

2018-06-08 10:13 UTC, pdavide approved these changes

2018-06-08 10:25 UTC, merged